title: demo
description: "Shards: Sandbox Pages"

baseurl: /demo
url: https://remino.github.io/

readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

exclude:
  - LICENSE.txt
  - jeksite

include:
  - .htaccess
